services:
  msvc-usuarios:
    container_name: msvc-usuarios
    image: alasstian/usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
#    env_file:
#      - ./msvc-usuarios/.env
    environment:
      PORT: 8001
      DB_HOST: localhost:5432
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: user
      DB_PASSWORD: pass
      CURSOS_URL: msvc_cursos:8002
    networks:
      - spring
#    depends_on:
#      - postgres
    restart: unless-stopped
  msvc-cursos:
    container_name: msvc-cursos
    image: alasstian/cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
#    env_file:
#      - ./msvc-cursos/.env
    environment:
      PORT: 8002
      DB_HOST: localhost:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: user
      DB_PASSWORD: pass
      USUARIOS_URL: msvc_usuarios:8001
    networks:
      - spring
    depends_on:
#      - postgres
      - msvc-usuarios
    restart: unless-stopped

networks:
  spring:
    driver: bridge
volumes:
  postgres:
  pgadmin: