apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 1
  selector:
    matchLabels:
      role: msvc-cursos
  template:
    metadata:
      labels:
        role: msvc-cursos
    spec:
      containers:
        - name: cursos
          image: alasstian/cursos:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: port
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_host
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: db_database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: msvc-cursos
                  key: db_password
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  name: msvc-cursos
                  key: usuarios_url
#          readinessProbe:
#            httpGet:
#              port: 8001
#              path: /actuator/health/readiness
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 25
#            timeoutSeconds: 15
#          livenessProbe:
#            httpGet:
#              port: 8001
#              path: /actuator/health/readiness
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 25
#            timeoutSeconds: 15
#          resources:
#            requests:
#              memory: "512Mi"
#              cpu: "500m"
#            limits:
#              memory: "900Mi"
#              cpu: "900m"
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-cursos
spec:
  ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
  type: LoadBalancer
  selector:
    role: msvc-cursos

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres:5432"
  db_database: "msvc_cursos"
  usuarios_url: "msvc_usuarios:8001"

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  db_username: dXNlcg==
  db_password: cGFzcw==